// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmzzblqdbonhfwzlrdmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptenpibHFkYm9uaGZ3emxyZG1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDM1ODYsImV4cCI6MjA2OTc3OTU4Nn0.TyJ5onOVPd8jnd5RqYYdk7_codLGS7nqCysiSU1dbAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});